default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: memorial_development

test:
  <<: *default
  database: memorial_test

production:
  <<: *default
  database: memorial_production
  username:
  password:
