default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: memori_development

test:
  <<: *default
  database: memori_test

production:
  <<: *default
  database: memori_production
  username:
  password:
